djangochat/chatbot/urls.py
from django.urls import path
from chatbot.views import index, ask_question, faq

APP_NAME = 'blog'

urlpatterns = [
    # Página principal onde o partial é carregado
    path('', index, name='index'),
    # URL para a requisição AJAX
    path('ask/', ask_question, name='ask_question'),
    # URL para a página de FAQ
    path('faq/', faq, name='faq'),
]

djangochat/django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('chatbot.urls', 'chatbot'), namespace='chatbot')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

djangochat/chatbot/models.py
from django.db import models

# Create your models here.

djangochat/chatbot/views.py
from django.shortcuts import render
from django.http import JsonResponse
from chatbot.ai.chatbot_model import ChatbotAI
from django.core.cache import cache


def index(request):
    # Certifique-se de que a página onde o partial será renderizado está aqui
    return render(request, 'chatbot/pages/index.html')


def ask_question(request):
    if request.method == 'POST':
        import json
        data = json.loads(request.body)
        question = data.get('question', '')

        chatbot = ChatbotAI()  # Instância do modelo de IA
        response = chatbot.get_response(question)  # Obtém a resposta da IA

        # Retorna a resposta para o cliente
        return JsonResponse({'response': response})

    return JsonResponse({'response': 'Método não permitido.'}, status=405)


def faq(request):
    # Tenta recuperar os dados do FAQ do cache
    faq_data = cache.get('faq_data')

    if not faq_data:
        # Se os dados não estão no cache, calcula e armazena no cache
        chatbot = ChatbotAI(retrain=False)  # Instancia o chatbot
        # Exemplo: lista de tuplas (pergunta, frequência)
        frequent_questions = chatbot.get_most_frequent_questions()

        # Inicializa uma lista para armazenar perguntas, respostas e contagem
        questions_and_answers = []

        # Calcula as respostas para cada pergunta frequente
        for question, count in frequent_questions:
            response = chatbot.get_response(question)
            questions_and_answers.append({
                'question': question,
                'response': response,
                'count': count
            })

        # Armazena os dados no cache por 10 minutos (600 segundos)
        cache.set('faq_data', questions_and_answers, timeout=600)

        # Passa os dados para o template
        faq_data = questions_and_answers

    # Retorna os dados para o template
    return render(request, 'chatbot/pages/faq.html', {
        # Passa a lista de perguntas, respostas e contagem
        'questions_and_answers': faq_data,
    })

djangochat/chatbot/templates/chatbot/base.html
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  {% include 'chatbot/partials/_head.html' %}
  {% block additional_head %}{% endblock additional_head %}
</head>
<body>
    {% include "chatbot/partials/_nav.html" %}
    {% include "chatbot/partials/_preset.html" %}
    {% block content %}{% endblock content %}
    {% include "chatbot/partials/_contact.html" %}
    {% include "chatbot/partials/_footer.html" %}
</body>
</html>

djangochat/chatbot/templates/chatbot/pages/faq.html
{% extends 'chatbot/base.html' %}

{% block content %}
    <div class="faq-container">
        <h1>Perguntas Frequentes</h1>

        {% if questions_and_answers %}
            <div class="faq-list">
                {% for item in questions_and_answers %}
                    <div class="faq-item">
                        <h3>{{ item.question }}</h3>
                        <p class="faq-response"><strong>Resposta:</strong> {{ item.response }}</p>
                        <p class="similar-questions">{{ item.count }} Perguntas Similares</p>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>Não há perguntas frequentes ainda.</p>
        {% endif %}
    </div>
{% endblock content %}

djangochat/chatbot/templates/chatbot/pages/index.html
{% extends 'chatbot/base.html' %}
{% block content %}
    {% include "chatbot/partials/_chatbot.html" %}
{% endblock content %}

djangochat/chatbot/templates/chatbot/partials/_chatbot.html
<div class="chat-container">
    <div class="chat-box" id="chat-box">
        <div class="message bot">
            <div class="message-avatar">🤖</div>
            <div class="message-content">Olá! Como posso ajudá-lo hoje?</div>
        </div>
    </div>
    <div class="input-container">
        <input type="text" class="form-control" id="user-input" placeholder="Digite sua pergunta..." onfocus="highlightButton()" onblur="resetButton()">
        <button id="send-button" class="btn btn-primary" onclick="sendMessage()">Enviar</button>
    </div>
</div>

djangochat/chatbot/templates/chatbot/partials/_contact.html
<section id="contact" class="container my-5">
    <h2 class="text-center mb-4">Contato</h2>
    <p class="text-center">E-mail: contato@chatbotdesaude.com | Telefone: (11) 1234-5678</p>
</section>

djangochat/chatbot/templates/chatbot/partials/_footer.html
<footer>
    <p>&copy; 2024 Chatbot de Saúde. Todos os direitos reservados.</p>
    <p><a href="#">Política de Privacidade</a> | <a href="#">Termos de Uso</a></p>
</footer>

djangochat/chatbot/templates/chatbot/partials/_head.html
{% load static %}
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" 
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" 
    crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'chatbot/css/main_css.css' %}">
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
<script src="{% static "chatbot/scripts/script.js" %}" defer></script>

<link rel="shortcut icon" href="{% static 'chatbot/icon/bot.png' %}" type="image/png">

<title>TigrAI - ChatBot de Saúde</title>

djangochat/chatbot/templates/chatbot/partials/_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url "chatbot:index" %}">Chatbot de Saúde</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item"><a class="nav-link" href="{% url "chatbot:faq" %}">FAQ</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url "chatbot:index" %}">Login</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url "chatbot:index" %}">Cadastro</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url "chatbot:index" %}">Sobre nós</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url "chatbot:index" %}">Contato</a></li>
        </ul>
    </div>
</nav>

djangochat/chatbot/templates/chatbot/partials/_preset.html
<section id="objectives" class="container my-5">
    <h2 class="text-center mb-4">Objetivos</h2>
    <div class="row">
        <div class="col-md-4">
            <div class="card text-center custom-card">
                <div class="card-body">
                    <h5 class="card-title">Facilitar o Acesso</h5>
                    <p class="card-text">
                        Tornar informações de saúde acessíveis a todos de forma prática e rápida.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-center custom-card">
                <div class="card-body">
                    <h5 class="card-title">Conectar Pacientes</h5>
                    <p class="card-text">
                        Aproximar pacientes e profissionais com ferramentas digitais eficientes.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-center custom-card">
                <div class="card-body">
                    <h5 class="card-title">Suporte Técnico</h5>
                    <p class="card-text">
                        Oferecer soluções técnicas para melhorar a experiência em saúde digital.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>    